export const NEWS_ALL_REQUEST = 'NEWS_ALL_REQUEST';
export const NEWS_ALL_SUCCESS = 'NEWS_ALL_SUCCESS';
export const NEWS_ALL_FAILURE = 'NEWS_ALL_FAILURE';

export const CREATE_NEWS_REQUEST = 'CREATE_NEWS_REQUEST';
export const CREATE_NEWS_SUCCESS = 'CREATE_NEWS_SUCCESS';
export const CREATE_NEWS_FAILURE = 'CREATE_NEWS_FAILURE';

export const DELETE_NEWS_REQUEST = 'DELETE_NEWS_REQUEST';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const DELETE_NEWS_FAILURE = 'DELETE_NEWS_FAILURE';

export const DETAIL_NEWS_REQUEST = 'DETAIL_NEWS_REQUEST';
export const DETAIL_NEWS_SUCCESS = 'DETAIL_NEWS_SUCCESS';
export const DETAIL_NEWS_FAILURE = 'DETAIL_NEWS_FAILURE';

export const EDIT_NEWS_REQUEST = 'EDIT_NEWS_REQUEST';
export const EDIT_NEWS_SUCCESS = 'EDIT_NEWS_SUCCESS';
export const EDIT_NEWS_FAILURE = 'EDIT_NEWS_FAILURE';